# Generated by Django 2.2.6 on 2021-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20210419_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lend',
        ),
        migrations.AddField(
            model_name='friend',
            name='lent',
            field=models.ManyToManyField(blank=True, null=True, to='p_library.Book'),
        ),
    ]
